backend:
  name: github
  repo: jamiepotepa/gatsby-blog

publish_mode: editorial_workflow

media_folder: src/assets
public_folder: /assets

collections:
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: postType, label: Post Type, widget: select, options: ['Post', 'Portfolio']}
      - { name: date, label: Created At, widget: date }
      - { name: image, label: Image, widget: image, required: false }
      - { name: body, label: Post, widget: markdown }
  - name: portfolio
    label: Portfolio
    folder: src/portfolio
    create: true
    fields:
      - { name: title, label: Title }
      - { name: postType, label: Post Type, widget: select, options: ['Portfolio', 'Post']}
      - { name: image, label: Header Image, widget: image, required: false }
      - { name: client, label: Client, widget: string, required: false }
      - { name: body, label: Body, widget: markdown }